import fs from "node:fs";
import path from "node:path";
import { NextRequest, NextResponse } from "next/server";
import { readStore } from "@/lib/store";

export const runtime = "nodejs";

const CONTENT_TYPES: Record<string, string> = {
  ".osz": "application/x-osu-beatmap-archive",
  ".osu": "text/plain; charset=utf-8",
  ".json": "application/json",
  ".txt": "text/plain; charset=utf-8",
  ".log": "text/plain; charset=utf-8",
};

export async function GET(
  _request: NextRequest,
  context: { params: Promise<{ id: string; artifactId: string }> },
) {
  const { id, artifactId } = await context.params;
  const job = readStore().jobs.find((j) => j.id === id);
  if (!job) return NextResponse.json({ error: "Job not found" }, { status: 404 });

  const artifact = job.artifacts.find((a) => a.id === artifactId);
  if (!artifact) return NextResponse.json({ error: "Artifact not found" }, { status: 404 });

  if (new Date(artifact.expiresAt).getTime() < Date.now()) {
    return NextResponse.json({ error: "Artifact expired" }, { status: 410 });
  }
  if (!artifact.relativePath) {
    return NextResponse.json({ error: "Artifact has no file path." }, { status: 500 });
  }

  // Artifact paths are generated by this app, but keep them inside .data anyway.
  const artifactRoot = path.join(process.cwd(), ".data", "artifacts");
  const absolute = path.resolve(process.cwd(), artifact.relativePath);
  if (!absolute.startsWith(artifactRoot) || !fs.existsSync(absolute)) {
    return NextResponse.json({ error: "Artifact file is missing." }, { status: 404 });
  }

  return new NextResponse(new Uint8Array(fs.readFileSync(absolute)), {
    status: 200,
    headers: {
      "Content-Type":
        CONTENT_TYPES[path.extname(artifact.fileName).toLowerCase()] ?? "application/octet-stream",
      "Content-Disposition": `attachment; filename="${artifact.fileName}"`,
      "Cache-Control": "no-store",
    },
  });
}
